# Generated by Django 3.2 on 2021-06-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
