# Generated by Django 3.2 on 2021-06-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_applicant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='name',
        ),
    ]
