# Generated by Django 3.2.2 on 2021-05-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('age', models.IntegerField()),
                ('introduce', models.TextField()),
                ('gender', models.CharField(choices=[('남자', '남자'), ('여자', '여자')], max_length=2)),
            ],
        ),
    ]
