# Generated by Django 3.2 on 2021-05-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='resume submitted'),
        ),
    ]
