# Generated by Django 3.2 on 2021-05-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0002_applicant_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(null=True, upload_to='resume_img/'),
        ),
    ]
