# Generated by Django 3.2 on 2021-06-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0003_applicant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='resume_img/'),
        ),
    ]
